version: "2"
run:
  issues-exit-code: 1
  tests: false
linters:
  enable:
    - gosec
    - perfsprint
    - prealloc
    - protogetter
    - usestdlibvars
  disable:
    - depguard
    - unused
  settings:
    gosec:
      excludes:
        - G115 # conversion_overflow panics on rune constants (https://github.com/securego/gosec/issues/1502)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
